version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ./:/apps
            - ./volumnes/postgresql/data/:/var/lib/postgresql/data

### Workspace Utilities Container ###########################
    workspace:
        build:
            context: ./workspace
        volumes_from:
            - applications
        ports:
           - "8080:8080"
#        entrypoint:
#          - /docker-entrypoint.sh
        tty: true
