version: '2'

services:

### Applications Code Container #############################
    applications:
        image: tianon/true
        volumes:
            - ./../api:/apps/api
            - ../cli:/apps/cli
            - ../web:/code/web
            - ../web-dev:/code/web-dev
            - ../webdev:/code/web-dev
            - ../volumes/postgresql/data:/var/lib/postgresql/data

### Python Container
    python:
        build: ./python
        volumes_from:
            - applications
        ports:
          - "8080:8080"
        links:
          - postgres

### PostgreSQL Container ####################################
    postgres:
        build: ./postgres
        volumes_from:
            - applications
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: vgstats
            POSTGRES_USER: vgstats
